# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_UcZiZSIN3iVYfm9msaXEdvEE5bGsh1
"""

# config.py

# 사용할 YOLO 모델 파일 경로
# MODEL_PATH = "yolo11n.pt"
# MODEL_PATH = "yolo26n.pt"
# MODEL_PATH = "guide_dog_yolo9_best_epoch20.pt"
# MODEL_PATH = "50eopch(SGD)best.pt"
# MODEL_PATH = "lessclasses.pt"
# MODEL_PATH = "5_16.pt"
MODEL_PATH = "yolo26n_5.pt"

# 사용할 카메라 번호
# 카메라,프레임 가로 세로, 버퍼 크기
CAMERA_INDEX = 0
FRAME_WIDTH = 600
FRAME_HEIGHT = 480
BUFFER_SIZE = 1

# YOLO 모델 입력 이미지 크기
IMG_SIZE = 320                # 객체 탐지 신뢰도 기준
CONFIDENCE_THRESHOLD = 0.5    # 0.5면 confidence가 50% 이상인 객체만 사용

# OpenCV 화면 창 이름
# 출력 화면 창의 가로,세로 크기
WINDOW_NAME = "Obstacle Detection"
WINDOW_WIDTH = FRAME_WIDTH
WINDOW_HEIGHT = FRAME_HEIGHT

# 멈춤 상태에서 계속 멈춤 명령을 유지하는 시간 (초)
STOP_HOLD_TIME_SEC = 2

# ==============================
# STM32 command mapping
# ==============================

COMMAND_TO_CHAR = {
    "FREE": "F",
    "STOP": "S",
    "TURN_LEFT": "L",
    "TURN_RIGHT": "R",
}

# ==============================
# Stabilization settings
# ==============================

#YOLO가 감지한 물체를 *초 동안 기억함
DETECTION_MEMORY_HOLD_TIME_SEC = 0.5

# ==============================
# Path planner / obstacle avoidance settings
# ==============================

# 초음파 센서 거리 기준(cm)
AVOID_DISTANCE_CM = 100.0     # 이 거리보다 가까우면 YOLO 박스 위치와 함께 회피 방향을 계산 예: 100cm 이내에 사람이 있으면 미리 왼쪽/오른쪽 회피 판단

# 명령 최소 전송 간격(sec)
# 0.2초면 초당 최대 5번 명령 전송
COMMAND_INTERVAL_SEC = 0.2

# 박스 크기를 위험도로 바꿀 때 나누는 값
# 박스 면적을 그대로 위험도에 쓰면 값이 너무 큼
# 값이 작을수록 box area가 danger에 더 크게 반영됨 danger = box_area / BOX_AREA_SCALE
# 박스 면적 10000 정도를 위험도 1점
BOX_AREA_SCALE = 10000.0

# ==============================
# Improved danger planner settings
# ==============================

VISIBLE_OBJECT_MIN_AREA = 1000

# 객체가 처음 위험하다고 판단되는 기준
MIN_BOX_AREA_BY_CLASS = {
    "person": 192000,
    "dog": 120000,
    "car": 192000,
    "furniture": 192000,
    "portable_object": 120000
}

# 위 딕셔너리에 없는 클래스가 감지되었을 때 사용할 기본 최소 박스 면적
DEFAULT_MIN_BOX_AREA = 120000

# 회피 중일 때, 이 비율보다 작아져야 장애물이 사라졌다고 판단
# 예: 0.4면 시작 기준의 40% 이하가 되어야 clear
CLEAR_BOX_AREA_RATIO = 0.4

# 회전 명령을 최소한 유지할 시간
TURN_HOLD_TIME_SEC = 1.0


# ==============================
# STM32 test mode
# ==============================

USE_STM32 = True   # True = real STM32, False = test without STM32
USE_ULTRASONIC = False

FAKE_DISTANCES_CM = {
    "FRONT": 150.0
}


